[package]
name = "udsdump-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
udsdump-common = { path = "../udsdump-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "udsdump"
path = "src/main.rs"
